/**
 * Copyright (c) 2024 Araf Karsh Hamid
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * <p>
 * This program and the accompanying materials are dual-licensed under
 * either the terms of the Eclipse Public License v1.0 as published by
 * the Eclipse Foundation
 * <p>
 * or (per the licensee's choosing)
 * <p>
 * under the terms of the Apache 2 License version 2.0
 * as published by the Apache Software Foundation.
 */
package test.fusion.water.order.copilot.mockito3;

import io.fusion.water.order.adapters.service.WarehouseServiceImpl;
import io.fusion.water.order.domain.models.OrderEntity;
import io.fusion.water.order.domain.models.OrderStatus;
import io.fusion.water.order.domain.services.PackingService;
import io.fusion.water.order.domain.services.ShippingService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import test.fusion.water.order.utils.OrderMock;

import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.when;


/**
 * ms-test-quickstart / WarehouseServiceEx3Test 
 *
 * @author: Araf Karsh Hamid
 * @version: 0.1
 * @date: 2024-12-26T3:28 PM
 */

@ExtendWith(MockitoExtension.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(OrderAnnotation.class)
class WarehouseServiceEx3Test {

    @Mock
    private PackingService packingService;

    @Mock
    private ShippingService shippingService;

    @InjectMocks
    private WarehouseServiceImpl warehouseService;

    @Test
    @DisplayName("Process Orders - All Orders Packed")
    @Order(1)
    @Tag("critical")
    void processOrdersAllPacked() {
        // Changed the Method Name createOrderPacked() to createPackedOrders()
        List<OrderEntity> packedOrders = OrderMock.createPackedOrders(OrderMock.createOrder());
        when(packingService.packOrders(packedOrders)).thenReturn(packedOrders);
        when(shippingService.shipOrder(packedOrders)).thenReturn(packedOrders);

        List<OrderEntity> processedOrders = warehouseService.processOrders(packedOrders);

        // Autogenerated Code Changed
        // Change the Condition to ORDERS_PACKED instead of IN_TRANSIT
        for (OrderEntity order : processedOrders) {
            assertEquals(OrderStatus.ORDER_PACKED, order.getOrderStatus());
        }
    }

    @Test
    @DisplayName("Process Orders - Some Orders Packed")
    @Order(2)
    @Tag("critical")
    void processOrdersSomePacked() {
        List<OrderEntity> mixedOrders = createMixedOrders();
        when(packingService.packOrders(mixedOrders)).thenReturn(mixedOrders);
        when(shippingService.shipOrder(mixedOrders)).thenReturn(mixedOrders);

        List<OrderEntity> processedOrders = warehouseService.processOrders(mixedOrders);

        // Autogenerated Code Changed
        // Change the Condition to ORDERS_PACKED instead of IN_TRANSIT
        for (OrderEntity order : processedOrders) {
            if (order.getOrderStatus() == OrderStatus.PREPARING) {
                assertEquals(OrderStatus.PREPARING, order.getOrderStatus());
            } else {
                assertEquals(OrderStatus.ORDER_PACKED, order.getOrderStatus());
            }
        }
    }

    @Test
    @DisplayName("Process Orders - All Orders Preparing")
    @Order(3)
    @Tag("critical")
    void processOrdersAllPreparing() {
        List<OrderEntity> preparingOrders = OrderMock.createOrder();
        when(packingService.packOrders(preparingOrders)).thenReturn(preparingOrders);
        when(shippingService.shipOrder(preparingOrders)).thenReturn(preparingOrders);

        List<OrderEntity> processedOrders = warehouseService.processOrders(preparingOrders);

        for (OrderEntity order : processedOrders) {
            assertEquals(OrderStatus.PREPARING, order.getOrderStatus());
        }
    }

    @Test
    @DisplayName("Process Orders - Empty List")
    @Order(4)
    @Tag("critical")
    void processOrdersEmptyList() {
        // Changed Autogenerated Code createEmptyOrderList to new ArrayList
        List<OrderEntity> emptyList = new ArrayList<>();
        List<OrderEntity> processedOrders = warehouseService.processOrders(emptyList);

        assertTrue(processedOrders.isEmpty());
    }

    @Test
    @DisplayName("Process Orders - Null List")
    @Order(5)
    @Tag("critical")
    void processOrdersNullList() {
        List<OrderEntity> processedOrders = warehouseService.processOrders(null);

        assertNull(processedOrders);
    }

    private List<OrderEntity> createMixedOrders() {
        List<OrderEntity> orderList = OrderMock.createOrder();
        orderList.get(0).orderPacked();
        orderList.get(1).orderIsGettingPrepared();
        return orderList;
    }
}
